# Generated by Django 3.1 on 2020-08-27 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20200827_1953'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='nome',
            new_name='name',
        ),
    ]
