# Generated by Django 3.1 on 2020-08-27 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20200827_2011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='nome',
            new_name='name',
        ),
    ]
